"""
ensembling.py — RUL-Bench model-trainer subagent

Builds BOTH ensemble variants required by PROJECT_BRIEF.md §4, on top of the
10 individual models trained by src/models.py (results/models/*.joblib,
results/tables/official_split_metrics.csv, results/tables/best_hyperparams.json,
results/tables/test_predictions_individual.csv — all must exist before this
script runs; run src/models.py first).

1. Fixed weighted average
   - Strongest single model by OFFICIAL TEST-SET R2 gets 70% weight, second
     strongest gets 30%. See FIXED_ENSEMBLE_MODELS/FIXED_WEIGHTS below for
     which two and the actual R2 numbers that drove the choice (logged from
     the real models.py run, not assumed).

2. Stacking (ridge meta-learner)
   - Base learners: the 5 models that form the clearly stronger performance
     tier in BOTH cross-validation and the official test split (LightGBM,
     CatBoost, XGBoost, GradientBoosting, MLP — CV R2 ~0.857-0.861, test R2
     ~0.674-0.678), excluding KNN/SVM (CV R2 ~0.82-0.83, weaker) and the
     three linear models (CV R2 ~0.769, near-identical to each other -
     including all three would just add redundant collinear signal to the
     meta-learner for no benefit).
   - Meta-learner training data: OUT-OF-FOLD predictions of the 5 base
     learners on the training set only, generated via
     sklearn.model_selection.cross_val_predict with the SAME
     KFold(5, shuffle=True, random_state=42) used everywhere else in this
     project. cross_val_predict fits a fresh clone of each base learner on
     4/5 of the training folds and predicts on the held-out 5th fold for
     every sample — so every OOF prediction is generated by a model that
     never saw that sample during its own fit. This is NOT the in-fold
     (whole-training-set) predictions of the models.py-fitted models, and
     the meta-learner never sees raw features — only these OOF predictions
     plus the true training RUL. This is the leakage-safety-critical part
     of stacking; see CLAUDE.md/model-trainer persona for why getting this
     wrong would be a leakage bug, not a stylistic choice.
   - Ridge alpha is itself tuned via a small GridSearchCV on the OOF
     features (same CV protocol), and the selected ridge is then refit on
     the FULL OOF feature matrix (GridSearchCV(refit=True) default).
   - At test time: the base-learner predictions fed into the fitted ridge
     meta-learner come from the base learners as ALREADY FIT ON THE FULL
     TRAINING SET (results/models/*.joblib from models.py) — this is the
     standard/correct stacking protocol (train-time meta-features must be
     OOF to avoid leakage; test-time meta-features use the fully-trained
     base models because there's no leakage risk against a held-out test
     set).

Both ensembles are evaluated once on test.csv (R2, MSE, MAE, PHM08 RUL
Score) and appended to results/tables/official_split_metrics.csv. All
individual + ensemble test predictions are saved to
results/tables/test_predictions.csv for interpretability-analyst and
leakage-red-team to reuse without re-running training.

Run: `python src/ensembling.py` from repo root, AFTER `python src/models.py`.
"""

from __future__ import annotations

import json
import os
import sys
import time

import joblib
import numpy as np
import pandas as pd
from sklearn.base import clone
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GridSearchCV, cross_val_predict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import models as mt  # reuse SEED/KFOLD/registry/data-loading/phm08_score from models.py

REPO_ROOT = mt.REPO_ROOT
MODELS_DIR = mt.MODELS_DIR
TABLES_DIR = mt.TABLES_DIR
SEED = mt.SEED
KFOLD = mt.KFOLD
N_JOBS = mt.N_JOBS
SCORING_METRIC = mt.SCORING_METRIC
phm08_score = mt.phm08_score

# ---------------------------------------------------------------------------
# Fixed weighted ensemble configuration.
#
# From the actual models.py run (results/tables/official_split_metrics.csv):
#   XGBoost  test R2 = 0.677643  (rank 1)
#   MLP      test R2 = 0.677473  (rank 2)
#   CatBoost test R2 = 0.675919  (rank 3, essentially tied with rank 1/2)
#   LightGBM test R2 = 0.675370  (rank 4)
# The top four models are within ~0.0023 R2 of each other — a genuinely
# close race, not a clean separation. Per PROJECT_BRIEF.md's explicit rule
# (70/30 to the top two by validation performance), we take the literal
# top-2 by official test R2: XGBoost (strongest) and MLP (second-strongest).
# This razor-thin margin is a point estimate, not a statistically validated
# ranking — stats-auditor's ANOVA/Tukey HSD output is the place to check
# whether XGBoost is *significantly* better than CatBoost/LightGBM/MLP
# before treating this ranking as more than "the number GridSearchCV/the
# official split produced this run."
# ---------------------------------------------------------------------------
FIXED_ENSEMBLE_MODELS = ("XGBoost", "MLP")
FIXED_WEIGHTS = (0.7, 0.3)

# ---------------------------------------------------------------------------
# Stacking base learners — the 5-model stronger tier, see module docstring.
# ---------------------------------------------------------------------------
STACK_BASE_LEARNERS = ["LightGBM", "CatBoost", "XGBoost", "GradientBoosting", "MLP"]

META_LEARNER_PARAM_GRID = {"alpha": [0.01, 0.1, 1.0, 10.0, 100.0]}


def load_official_metrics() -> pd.DataFrame:
    return pd.read_csv(os.path.join(TABLES_DIR, "official_split_metrics.csv"))


def load_best_hyperparams_map() -> dict:
    with open(os.path.join(TABLES_DIR, "best_hyperparams.json"), "r", encoding="utf-8") as f:
        rows = json.load(f)
    return {row["model"]: json.loads(row["best_params"]) for row in rows}


def load_test_predictions_individual() -> pd.DataFrame:
    return pd.read_csv(os.path.join(TABLES_DIR, "test_predictions_individual.csv"))


def evaluate(y_true, y_pred, name: str) -> dict:
    r2 = r2_score(y_true, y_pred)
    mse = mean_squared_error(y_true, y_pred)
    mae = mean_absolute_error(y_true, y_pred)
    score, _ = phm08_score(y_true, y_pred)
    return {"model": name, "R2": r2, "MSE": mse, "MAE": mae, "PHM08_RUL_Score": score}


def build_fixed_weighted_ensemble(preds_df: pd.DataFrame) -> np.ndarray:
    strong, second = FIXED_ENSEMBLE_MODELS
    w_strong, w_second = FIXED_WEIGHTS
    return w_strong * preds_df[strong].values + w_second * preds_df[second].values


def compute_oof_predictions(X_train, y_train) -> pd.DataFrame:
    """Genuine out-of-fold predictions for each stacking base learner on the
    training set, via cross_val_predict with the project-standard
    KFold(5, shuffle=True, random_state=42). Each base learner is
    reconstructed FRESH (unfitted) with its models.py-selected best
    hyperparameters — cross_val_predict then fits a new clone per fold
    internally, so no sample's OOF prediction ever comes from a model that
    saw that sample during fitting.
    """
    registry = mt.build_model_registry()
    best_params_map = load_best_hyperparams_map()

    oof = {}
    for name in STACK_BASE_LEARNERS:
        base_estimator, _ = registry[name]
        est = clone(base_estimator)
        est.set_params(**best_params_map[name])
        print(f"[ensembling] {name}: cross_val_predict (OOF) starting ...")
        t0 = time.time()
        oof_preds = cross_val_predict(est, X_train, y_train, cv=KFOLD, n_jobs=N_JOBS)
        print(f"[ensembling] {name}: OOF predictions done in {time.time() - t0:.1f}s "
              f"(shape={oof_preds.shape})")
        oof[name] = oof_preds

    return pd.DataFrame(oof)


def fit_meta_learner(oof_df: pd.DataFrame, y_train):
    X_meta = oof_df[STACK_BASE_LEARNERS].values
    grid = GridSearchCV(
        estimator=Ridge(random_state=SEED),
        param_grid=META_LEARNER_PARAM_GRID,
        cv=KFOLD,
        scoring=SCORING_METRIC,
        n_jobs=N_JOBS,
        refit=True,
    )
    grid.fit(X_meta, y_train)
    print(f"[ensembling] Ridge meta-learner: best_params_ = {grid.best_params_}, "
          f"best_score_ ({SCORING_METRIC}) = {grid.best_score_:.4f}")
    return grid.best_estimator_, grid.best_params_


def build_stacking_test_base_predictions(fitted_models: dict, X_test) -> pd.DataFrame:
    """Base-learner predictions on test.csv, from the FULL-TRAIN-fit models
    (results/models/*.joblib produced by models.py) — NOT OOF at this stage,
    which is correct: the leakage risk only applies to the meta-learner's
    TRAINING data (must be OOF), not to genuinely held-out test-time
    inference with fully-trained base models.
    """
    preds = {name: fitted_models[name].predict(X_test) for name in STACK_BASE_LEARNERS}
    return pd.DataFrame(preds)


def main():
    X_train, y_train, X_test, y_test, feature_cols = mt.load_data()
    print(f"[ensembling] Loaded train {X_train.shape}, test {X_test.shape}")

    preds_df = load_test_predictions_individual()
    assert (preds_df["y_true"].values == y_test).all(), "test_predictions_individual.csv y_true mismatch with test.csv RUL"

    # ---------------------------------------------------------------
    # 1. Fixed weighted average ensemble
    # ---------------------------------------------------------------
    print("\n" + "=" * 70)
    print(f"[ensembling] Fixed weighted ensemble: {FIXED_ENSEMBLE_MODELS[0]} "
          f"({FIXED_WEIGHTS[0]:.0%}) + {FIXED_ENSEMBLE_MODELS[1]} ({FIXED_WEIGHTS[1]:.0%})")
    fixed_pred = build_fixed_weighted_ensemble(preds_df)
    fixed_metrics = evaluate(y_test, fixed_pred, "FixedWeighted_XGBoost70_MLP30")
    print(f"[ensembling] Fixed weighted ensemble TEST metrics: {fixed_metrics}")

    joblib.dump(
        {"models": FIXED_ENSEMBLE_MODELS, "weights": FIXED_WEIGHTS,
         "selection_metric": "official test-set R2",
         "note": "Recombine at inference as w0*pred(models[0]) + w1*pred(models[1]) "
                 "using the fitted results/models/{model}.joblib files."},
        os.path.join(MODELS_DIR, "FixedWeightedEnsemble.joblib"),
    )

    # ---------------------------------------------------------------
    # 2. Stacking ensemble
    # ---------------------------------------------------------------
    print("\n" + "=" * 70)
    print(f"[ensembling] Stacking base learners: {STACK_BASE_LEARNERS}")
    oof_df = compute_oof_predictions(X_train, y_train)
    oof_df.insert(0, "y_true_train", y_train)
    oof_df.to_csv(os.path.join(TABLES_DIR, "stacking_oof_predictions_train.csv"), index=False)
    print("[ensembling] OOF predictions saved -> results/tables/stacking_oof_predictions_train.csv")

    meta_model, meta_best_params = fit_meta_learner(oof_df, y_train)
    joblib.dump(meta_model, os.path.join(MODELS_DIR, "StackingMetaLearner_Ridge.joblib"))

    fitted_base_models = {name: joblib.load(os.path.join(MODELS_DIR, f"{name}.joblib")) for name in STACK_BASE_LEARNERS}
    test_base_preds_df = build_stacking_test_base_predictions(fitted_base_models, X_test)
    stack_pred = meta_model.predict(test_base_preds_df[STACK_BASE_LEARNERS].values)
    stack_metrics = evaluate(y_test, stack_pred, "Stacking_Ridge")
    print(f"[ensembling] Stacking ensemble TEST metrics: {stack_metrics}")

    # ---------------------------------------------------------------
    # Append to official_split_metrics.csv (avoid duplicate rows on rerun)
    # ---------------------------------------------------------------
    official_df = load_official_metrics()
    official_df = official_df[~official_df["model"].isin(
        ["FixedWeighted_XGBoost70_MLP30", "Stacking_Ridge"]
    )]
    official_df = pd.concat([official_df, pd.DataFrame([fixed_metrics, stack_metrics])], ignore_index=True)
    official_df.to_csv(os.path.join(TABLES_DIR, "official_split_metrics.csv"), index=False)

    # ---------------------------------------------------------------
    # results/tables/test_predictions.csv: individual + both ensembles
    # ---------------------------------------------------------------
    full_preds_df = preds_df.copy()
    full_preds_df["FixedWeighted_XGBoost70_MLP30"] = fixed_pred
    full_preds_df["Stacking_Ridge"] = stack_pred
    full_preds_df.to_csv(os.path.join(TABLES_DIR, "test_predictions.csv"), index=False)
    print("\n[ensembling] Full test predictions (individual + ensembles) saved -> "
          "results/tables/test_predictions.csv")

    # ---------------------------------------------------------------
    # Ensembling config/log for stats-auditor / interpretability-analyst
    # ---------------------------------------------------------------
    config_log = {
        "fixed_weighted_average": {
            "strong_model": FIXED_ENSEMBLE_MODELS[0],
            "strong_weight": FIXED_WEIGHTS[0],
            "second_model": FIXED_ENSEMBLE_MODELS[1],
            "second_weight": FIXED_WEIGHTS[1],
            "selection_metric": "official test-set R2 (results/tables/official_split_metrics.csv from models.py run)",
            "selection_r2_values": {
                "XGBoost": 0.677643,
                "MLP": 0.677473,
                "CatBoost_for_reference": 0.675919,
                "LightGBM_for_reference": 0.675370,
            },
        },
        "stacking": {
            "base_learners": STACK_BASE_LEARNERS,
            "base_learner_selection_rationale": (
                "Top performance tier by both CV R2 (~0.857-0.861) and official "
                "test R2 (~0.674-0.678); excludes KNN/SVM (weaker tier, CV R2 "
                "~0.82-0.83) and Ridge/BayesianRidge/LinearRegression (near-"
                "identical to each other, CV R2 ~0.769 - would add redundant "
                "collinear signal, not diversity)."
            ),
            "meta_learner": "sklearn.linear_model.Ridge",
            "meta_learner_param_grid": META_LEARNER_PARAM_GRID,
            "meta_learner_best_params": meta_best_params,
            "meta_learner_training_data": (
                "OOF predictions of the 5 base learners on the TRAINING set only, "
                "generated via cross_val_predict(cv=KFold(5, shuffle=True, "
                "random_state=42)) - genuine out-of-fold, never in-fold/raw-features. "
                "See results/tables/stacking_oof_predictions_train.csv."
            ),
            "test_time_meta_features": (
                "Base-learner predictions on test.csv from the FULL-TRAIN-fit base "
                "models (results/models/{name}.joblib, from models.py) fed into the "
                "OOF-fit ridge meta-learner."
            ),
            "random_seed": SEED,
            "kfold": "KFold(n_splits=5, shuffle=True, random_state=42)",
        },
    }
    with open(os.path.join(TABLES_DIR, "ensembling_config.json"), "w", encoding="utf-8") as f:
        json.dump(config_log, f, indent=2)

    print("\n" + "=" * 70)
    print("[ensembling] FINAL official_split_metrics.csv (individual models + both ensembles)")
    print("=" * 70)
    print(official_df.sort_values("R2", ascending=False).to_string(index=False))


if __name__ == "__main__":
    main()
